export default [
  { id: 1, name: "JavaScript" },
  { id: 2, name: "Node.js" },
  { id: 3, name: "React" },
  { id: 4, name: "HTML" },
  { id: 5, name: "CSS" },
  { id: 6, name: "Python" },
  { id: 7, name: "AWS" },
  { id: 8, name: "Docker" },
  { id: 9, name: "Kubernetes" },
  { id: 10, name: "Sass" },
  { id: 11, name: "React.js" },
  { id: 12, name: "MySQL" },
  { id: 13, name: "Express.js" },
  { id: 14, name: "REST APIs" },
  { id: 15, name: "User Authentication" },
  { id: 16, name: "OAuth" },
  { id: 17, name: "Ruby" },
  { id: 18, name: "Ruby on Rails" },
  { id: 19, name: "RubyGems" },
  { id: 20, name: "RSpec" },
  { id: 21, name: "Rubocop" },
  { id: 22, name: "PostgreSQL" },
  { id: 23, name: "MongoDB" },
  { id: 24, name: "Redis" },
  { id: 25, name: "GitHub" },
  { id: 26, name: "GitLab" },
  { id: 27, name: "Heroku" },
  { id: 28, name: "GCP" },
  { id: 29, name: "Terraform" },
  { id: 30, name: "GitLab CI" },
  { id: 31, name: "Jira" },
  { id: 32, name: "TypeScript" },
  { id: 33, name: "Vue.js" },
  { id: 34, name: "Angular" },
  { id: 35, name: "GraphQL" },
  { id: 36, name: "jQuery" },
  { id: 37, name: "Tailwind CSS" },
  { id: 38, name: "Bootstrap" },
  { id: 39, name: "WebSockets" },
  { id: 40, name: "Nginx" },
  { id: 41, name: "Vagrant" },
  { id: 42, name: "Progressive Web Apps" },
  { id: 43, name: "Docker Compose" },
  { id: 44, name: "CI/CD" },
  { id: 45, name: "Jest" },
  { id: 46, name: "GraphQL Apollo" },
  { id: 47, name: "Next.js" },
  { id: 48, name: "Nuxt.js" },
  { id: 49, name: "Socket.io" },
  { id: 50, name: "Redux" }
];
