export default [
  {
    user_id: 1,
    role: "mentor",
    user_name: "John Doe",
    bio: "Experienced software developer and mentor with over 10 years in web development. Passionate about teaching and empowering others to achieve their goals in tech.",
    location: "New York, USA",
    profile_picture_url: "https://example.com/john.jpg",
    mode: "online",
    experience: "5+ years in front-end and back-end technologies (React, Node.js).",
    goals: "Help mentees become independent developers with a focus on best practices and career growth.",
  },
  {
    user_id: 2,
    role: "mentee",
    user_name: "Jane Smith",
    bio: "Aspiring software engineer with a strong foundation in computer science, transitioning into software development after a coding bootcamp.",
    location: "San Francisco, USA",
    profile_picture_url: "",
    mode: "in-person",
    experience: "Junior developer with experience in HTML, CSS, JavaScript, and React.",
    goals: "Learn full-stack development and secure a junior developer role in a tech company.",
  },
  {
    user_id: 3,
    role: "mentor",
    user_name: "Alice Cooper",
    bio: "Full-stack developer and tech lead with 8+ years of experience. Passionate about mentoring and helping others build their leadership skills.",
    location: "Los Angeles, USA",
    profile_picture_url: "",
    mode: "both",
    experience: "Tech Lead for 3 years, expert in JavaScript, React, Node.js.",
    goals: "Mentor mentees to develop leadership skills and become effective engineers.",
  },
  {
    user_id: 4,
    role: "mentee",
    user_name: "David Lee",
    bio: "Aspiring cloud architect with a focus on DevOps practices. Looking to expand knowledge in cloud infrastructure and automation.",
    location: "Seattle, USA",
    profile_picture_url: "",
    mode: "both",
    experience: "Junior DevOps engineer with exposure to AWS, GCP, and Terraform.",
    goals: "Learn to design and manage cloud infrastructure and automate workflows.",
  },
];

