export default [
  {
    user_id: 1,
    role: "mentor",
    name: "John Doe",
    bio: "Experienced developer and mentor",
    skills: JSON.stringify(["JavaScript", "Node.js", "React"]), // Ensure this is an array
    availability: JSON.stringify(["Mon", "Wed", "Fri"]), // Make sure this is an array
    areas_of_interest: JSON.stringify(["Mentorship", "Tech"]), // Make sure this is an array
    location: "New York",
    profile_picture_url: "https://example.com/john.jpg",
    mentoring_style: "Direct",
    previous_experience: "5+ years in tech",
    goals: "Help mentees become independent developers",
  },
  {
    user_id: 2,
    role: "mentee",
    name: "Jane Smith",
    bio: "Aspiring software engineer",
    skills: JSON.stringify(["HTML", "CSS", "JavaScript"]),
    availability: JSON.stringify(["Tue", "Thu"]),
    areas_of_interest: JSON.stringify(["Frontend Development", "UI/UX"]),
    location: "San Francisco",
    profile_picture_url: "https://example.com/jane.jpg",
    mentoring_style: "Collaborative",
    previous_experience: "Junior developer",
    goals: "Learn full-stack development",
  },
  {
    user_id: 3,
    role: "mentor",
    name: "Alice Cooper",
    bio: "Full-stack developer and tech lead",
    skills: JSON.stringify(["JavaScript", "Python", "AWS"]),
    availability: JSON.stringify(["Mon", "Wed", "Thu"]),
    areas_of_interest: JSON.stringify(["Leadership", "Tech"]),
    location: "Los Angeles",
    profile_picture_url: "https://example.com/alice.jpg",
    mentoring_style: "Guided",
    previous_experience: "Tech Lead for 3 years",
    goals: "Help mentees gain leadership skills",
  },
  {
    user_id: 4,
    role: "mentee",
    name: "David Lee",
    bio: "Aspiring cloud architect with a focus on DevOps",
    skills: JSON.stringify(["AWS", "Docker", "Kubernetes"]),
    availability: JSON.stringify(["Mon", "Tue", "Thu"]),
    areas_of_interest: JSON.stringify(["Cloud Architecture", "DevOps"]),
    location: "Seattle",
    profile_picture_url: "https://example.com/david.jpg",
    mentoring_style: "Hands-on",
    previous_experience: "Junior DevOps engineer",
    goals: "Learn how to design and manage cloud infrastructure",
  },
];
