export default [
  {
    user_id: 1,
    role: "mentor",
    name: "John Doe",
    bio: "Experienced developer and mentor",
    location: "New York",
    profile_picture_url: "https://example.com/john.jpg",
    mode: "online",
    experience: "5+ years in tech",
    goals: "Help mentees become independent developers",
  },
  {
    user_id: 2,
    role: "mentee",
    name: "Jane Smith",
    bio: "Aspiring software engineer",
    location: "San Francisco",
    profile_picture_url: "https://example.com/jane.jpg",
    mode: "in-person",
    experience: "Junior developer",
    goals: "Learn full-stack development",
  },
  {
    user_id: 3,
    role: "mentor",
    name: "Alice Cooper",
    bio: "Full-stack developer and tech lead",
    location: "Los Angeles",
    profile_picture_url: "https://example.com/alice.jpg",
    mode: "both",
    experience: "Tech Lead for 3 years",
    goals: "Help mentees gain leadership skills",
  },
  {
    user_id: 4,
    role: "mentee",
    name: "David Lee",
    bio: "Aspiring cloud architect with a focus on DevOps",
    location: "Seattle",
    profile_picture_url: "https://example.com/david.jpg",
    mode: "both",
    experience: "Junior DevOps engineer",
    goals: "Learn how to design and manage cloud infrastructure",
  },
];
